- NAME: variables from PLAY LEVEL
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      ms: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"