- name: checking data types
  hosts: localhost
  vars:
    NAME: Sivakumar #key value
    Skills: 
    - DevOps
    - Shell
    - Ansible
    - Linux
    Experience: # Expperience is map type. It contains keyi value pairs
      DevOps: 7
      AWS: 6
      Docker: 4
    Trainer: true #boolean
  tasks:
  - name: print eky valude pair
    ansible. builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
      msg: "is he Trainer: {{Trainer}}"